### ISSUE TITLE
onClick Method 

### ISSUE THREAD

**Issue by eymel** [FanFataL/swipe-controller-demo#7]
I want to use onclick when item clicked. how can I use onclick method?

**Comment by jerome2710** [comment]
Take a look at the [MainActivity.java](https://github.com/FanFataL/swipe-controller-demo/blob/master/app/src/main/java/pl/fanfatal/swipecontrollerdemo/MainActivity.java#L64). You may use the abstract class `SwipeControllerActions` to hook into click events.

**Comment by eymel** [comment]
I checked MainActivity. But I can't use click and left-right action together. These actions conflict with swipecontrolleractions click method.

**Comment by jerome2710** [comment]
These do not conflict with the SwipeControllerActions-methods. This class is an abstract class, which should be implemented in your activity like the [MainActivity example](https://github.com/FanFataL/swipe-controller-demo/blob/master/app/src/main/java/pl/fanfatal/swipecontrollerdemo/MainActivity.java#L64). The SwipeControllerActions-class should be left untouched.

**Comment by eymel** [comment]
Thank you for answer . For Example, I added SwipeControllerActions onClickItem but I can't catch this method because when I click Left or Right method . I change setItemsClickable in setTouchListener method  but not running. 
```
//SwipeControllerActions
public abstract class SwipeControllerActions {
    public void onLeftClicked(int position) {
    }

    public void onRightClicked(int position) {
    }

    public void onClickItem(int position) {
    }
}

//MainActivity
  swipeController = new SwipeController(new SwipeControllerActions() {
            @Override
            public void onRightClicked(int position) {
                baseActivity.replaceFragment(new Fragment());
            }

            @Override
            public void onClickItem(int position) {
                super.onClickItem(position);
            }

            @Override
            public void onLeftClicked(int position) {
                super.onLeftClicked(position);
            }
        });
        ItemTouchHelper itemTouchhelper = new ItemTouchHelper(swipeController);
        itemTouchhelper.attachToRecyclerView(recyclerView);
        recyclerViewDoctor.addItemDecoration(new RecyclerView.ItemDecoration() {
            @Override
            public void onDraw(Canvas c, RecyclerView parent, RecyclerView.State state) {
                swipeController.onDraw(c);
            }
            
        });
```

**Comment by vkovalch** [comment]
OnClick method will catch via holder of RecyclerView in onBindViewHolder.

public interface ClickItemListener {
    void OnItemClick(SomeModel someModel);
}

public class MainActivity extends AppCompatActivity implements ClickItemListener {

private  RecyclerView mRecyclerView;

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_main);
       mRecyclerView =  findViewById(R.id.somelist);
      mRecyclerView.recyclerView.setLayoutManager(new LinearLayoutManager(this));
      mRecyclerView.setAdapter(someAdapter(data, **this**));
        swipeController = new SwipeController(new SwipeControllerActions() {
            @Override
            public void onRightClicked(int position) {
                 //catch swipe 
            }

            @Override
            public void onLeftClicked(int position) {
                //catch swipe 
            }
        });

        ItemTouchHelper itemTouchhelper = new ItemTouchHelper(swipeController);
        itemTouchhelper.attachToRecyclerView(recyclerView);

        recyclerView.addItemDecoration(new RecyclerView.ItemDecoration() {
            @Override
            public void onDraw(Canvas c, RecyclerView parent, RecyclerView.State state) {
                swipeController.onDraw(c);
            }
        });
      . . . 
      }

    @Override
    public void OnItemClick(SomeModel someModel) {
           /// catch click
    }

}

public class SomeAdapter extends RecyclerView.Adapter<SomeAdapter.ViewHolder> {

private ClickItemListener mListener;
private List<SomeModel> data;
public SomeAdapter(List<SomeModel> data, ClickItemListener listener){
        this.data = data;
       this.mListener = listener;
    }

    @Override
    public void onBindViewHolder(@NonNull final ViewHolder holder, int position) {
         SomeModel sm = data.get(position) ;
        holder.someview.setOnClickListener(new View.OnClickListener() {
            @Override
            public void onClick(View view) {
                if (mListener!=null){
                    mListener.OnItemClick(sm);
                }
            }
        });
    }
...
}

**Comment by eymel** [comment]
Thank you for answer. I didn't resolve this problem because when swipe left or right setItemsClickable(false) run .  So I can't catch onclick method . I resolved this problem with https://medium.com/@kitek/recyclerview-swipe-to-delete-easier-than-you-thought-cff67ff5e5f6 this article.

**Comment by vkovalch** [comment]
I can help you, if U share you part copy of code? and i will edit your file
